//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ciddilibirşey
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAkademisyen
    {
        public int AkademisyenID { get; set; }
        public string AkademisyenAd { get; set; }
        public string AkademisyenSoyad { get; set; }
        public string AkademisyenKullanici { get; set; }
        public string AkademisyenSifre { get; set; }
        public int AkademisyenDers { get; set; }
    
        public virtual TblDersler TblDersler { get; set; }
    }
}
