//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ciddilibirşey
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotlar
    {
        public int NotID { get; set; }
        public int NotDers { get; set; }
        public int NotOgr { get; set; }
        public int NotVize { get; set; }
        public int NotFinal { get; set; }
        public int NotQuiz { get; set; }
        public int NotOrt { get; set; }
    
        public virtual TblDersler TblDersler { get; set; }
        public virtual TblOgrenciler TblOgrenciler { get; set; }
    }
}
